package org.md2k.mcerebrum.core.access.configinfo;

// @formatter:off
import org.md2k.mcerebrum.core.access.base.BaseModel;

import java.util.Date;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/**
 * Config ContentProvider Model class.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
@SuppressWarnings({"WeakerAccess", "unused"})
public interface ConfigInfoModel extends BaseModel {

    long getId();

    @Nullable
    String getCid();

    @Nullable
    String getType();

    @Nullable
    String getTitle();

    @Nullable
    String getSummary();

    @Nullable
    String getDescription();

    @Nullable
    String getVersions();

    @Nullable
    String getUpdates();

    @Nullable
    String getExpectedVersion();

    @Nullable
    String getLatestVersion();

    @Nullable
    String getDownloadFrom();

    @Nullable
    String getDownloadLink();
}
