package org.md2k.mcerebrum.core.access.configinfo;

// @formatter:off
import org.md2k.mcerebrum.core.access.base.BaseModel;

import java.util.Date;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/**
 * Config ContentProvider Bean class.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
@SuppressWarnings({"WeakerAccess", "unused", "ConstantConditions"})
public class ConfigInfoBean implements ConfigInfoModel {
    private long mId;
    private String mCid;
    private String mType;
    private String mTitle;
    private String mSummary;
    private String mDescription;
    private String mVersions;
    private String mUpdates;
    private String mExpectedVersion;
    private String mLatestVersion;
    private String mDownloadFrom;
    private String mDownloadLink;

    @Override
    public long getId() {
        return mId;
    }

    public void setId(long id) {
        mId = id;
    }

    @Nullable
    @Override
    public String getCid() {
        return mCid;
    }

    public void setCid(@Nullable String cid) {
        mCid = cid;
    }

    @Nullable
    @Override
    public String getType() {
        return mType;
    }

    public void setType(@Nullable String type) {
        mType = type;
    }

    @Nullable
    @Override
    public String getTitle() {
        return mTitle;
    }

    public void setTitle(@Nullable String title) {
        mTitle = title;
    }

    @Nullable
    @Override
    public String getSummary() {
        return mSummary;
    }

    public void setSummary(@Nullable String summary) {
        mSummary = summary;
    }

    @Nullable
    @Override
    public String getDescription() {
        return mDescription;
    }

    public void setDescription(@Nullable String description) {
        mDescription = description;
    }

    @Nullable
    @Override
    public String getVersions() {
        return mVersions;
    }

    public void setVersions(@Nullable String versions) {
        mVersions = versions;
    }

    @Nullable
    @Override
    public String getUpdates() {
        return mUpdates;
    }

    public void setUpdates(@Nullable String updates) {
        mUpdates = updates;
    }

    @Nullable
    @Override
    public String getExpectedVersion() {
        return mExpectedVersion;
    }

    public void setExpectedVersion(@Nullable String expectedVersion) {
        mExpectedVersion = expectedVersion;
    }

    @Nullable
    @Override
    public String getLatestVersion() {
        return mLatestVersion;
    }

    public void setLatestVersion(@Nullable String latestVersion) {
        mLatestVersion = latestVersion;
    }

    @Nullable
    @Override
    public String getDownloadFrom() {
        return mDownloadFrom;
    }

    public void setDownloadFrom(@Nullable String downloadFrom) {
        mDownloadFrom = downloadFrom;
    }

    @Nullable
    @Override
    public String getDownloadLink() {
        return mDownloadLink;
    }

    public void setDownloadLink(@Nullable String downloadLink) {
        mDownloadLink = downloadLink;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ConfigInfoBean bean = (ConfigInfoBean) o;
        return mId == bean.mId;
    }

    @Override
    public int hashCode() {
        return (int) (mId ^ (mId >>> 32));
    }

    @NonNull
    public static ConfigInfoBean newInstance(long id, @Nullable String cid, @Nullable String type, @Nullable String title, @Nullable String summary, @Nullable String description, @Nullable String versions, @Nullable String updates, @Nullable String expectedVersion, @Nullable String latestVersion, @Nullable String downloadFrom, @Nullable String downloadLink) {
        ConfigInfoBean res = new ConfigInfoBean();
        res.mId = id;
        res.mCid = cid;
        res.mType = type;
        res.mTitle = title;
        res.mSummary = summary;
        res.mDescription = description;
        res.mVersions = versions;
        res.mUpdates = updates;
        res.mExpectedVersion = expectedVersion;
        res.mLatestVersion = latestVersion;
        res.mDownloadFrom = downloadFrom;
        res.mDownloadLink = downloadLink;
        return res;
    }

    @NonNull
    public static ConfigInfoBean copy(@NonNull ConfigInfoModel from) {
        ConfigInfoBean res = new ConfigInfoBean();
        res.mId = from.getId();
        res.mCid = from.getCid();
        res.mType = from.getType();
        res.mTitle = from.getTitle();
        res.mSummary = from.getSummary();
        res.mDescription = from.getDescription();
        res.mVersions = from.getVersions();
        res.mUpdates = from.getUpdates();
        res.mExpectedVersion = from.getExpectedVersion();
        res.mLatestVersion = from.getLatestVersion();
        res.mDownloadFrom = from.getDownloadFrom();
        res.mDownloadLink = from.getDownloadLink();
        return res;
    }

    public static class Builder {
        private ConfigInfoBean mRes = new ConfigInfoBean();

        public Builder id(long id) {
            mRes.mId = id;
            return this;
        }

        public Builder cid(@Nullable String cid) {
            mRes.mCid = cid;
            return this;
        }

        public Builder type(@Nullable String type) {
            mRes.mType = type;
            return this;
        }

        public Builder title(@Nullable String title) {
            mRes.mTitle = title;
            return this;
        }

        public Builder summary(@Nullable String summary) {
            mRes.mSummary = summary;
            return this;
        }

        public Builder description(@Nullable String description) {
            mRes.mDescription = description;
            return this;
        }

        public Builder versions(@Nullable String versions) {
            mRes.mVersions = versions;
            return this;
        }

        public Builder updates(@Nullable String updates) {
            mRes.mUpdates = updates;
            return this;
        }

        public Builder expectedVersion(@Nullable String expectedVersion) {
            mRes.mExpectedVersion = expectedVersion;
            return this;
        }

        public Builder latestVersion(@Nullable String latestVersion) {
            mRes.mLatestVersion = latestVersion;
            return this;
        }

        public Builder downloadFrom(@Nullable String downloadFrom) {
            mRes.mDownloadFrom = downloadFrom;
            return this;
        }

        public Builder downloadLink(@Nullable String downloadLink) {
            mRes.mDownloadLink = downloadLink;
            return this;
        }

        public ConfigInfoBean build() {
            return mRes;
        }
    }

    public static Builder newBuilder() {
        return new Builder();
    }
}
