package org.md2k.mcerebrum.core.access.configinfo;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

import org.md2k.mcerebrum.core.access.SampleProviderSQLiteOpenHelper;
import org.md2k.mcerebrum.core.access.configinfo.ConfigInfoBean;
import org.md2k.mcerebrum.core.access.configinfo.ConfigInfoColumns;
import org.md2k.mcerebrum.core.access.configinfo.ConfigInfoContentValues;
import org.md2k.mcerebrum.core.access.configinfo.ConfigInfoCursor;
import org.md2k.mcerebrum.core.access.configinfo.ConfigInfoSelection;

/**
 * Config ContentProvider ContentProvider class.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
public class ConfigCP {
    public static void set(Context context, String cid, String type, String title, String summary, String description, String version, String update, String expectedVersion, String downloadLink, String fileName) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) configInfoBean=new ConfigInfoBean();
        configInfoBean.setCid(cid);
        configInfoBean.setType(type);
        configInfoBean.setTitle(title);
        configInfoBean.setSummary(summary);
        configInfoBean.setDescription(description);
        configInfoBean.setVersions(version);
        configInfoBean.setUpdates(update);
        configInfoBean.setExpectedVersion(expectedVersion);
        configInfoBean.setDownloadLink(downloadLink);
        insertOrUpdate(context, configInfoBean);
    }

    public static void deleteTable(Context context) {
        try {
            SampleProviderSQLiteOpenHelper s = SampleProviderSQLiteOpenHelper.getInstance(context);
            SQLiteDatabase db = s.getWritableDatabase();
            db.execSQL("DROP TABLE IF EXISTS " + ConfigInfoColumns.TABLE_NAME);
            db.execSQL(SampleProviderSQLiteOpenHelper.SQL_CREATE_TABLE_CONFIG_INFO);
        }catch (Exception e){

        }
    }

    private static void insertOrUpdate(Context context, ConfigInfoBean configInfoBean) {
        try {
            ConfigInfoContentValues values = prepare(configInfoBean);
            if (isEmpty(context))
                values.insert(context);
            else
                values.update(context, new ConfigInfoSelection().cid(configInfoBean.getCid()));
        }catch (Exception e){
            deleteTable(context);
            ConfigInfoContentValues values = prepare(configInfoBean);
            values.insert(context);
        }
    }

    private static ConfigInfoBean read(Context context) {
        ConfigInfoBean configInfoBean=null;
        try {
            ConfigInfoSelection configInfoSelection = new ConfigInfoSelection();
            ConfigInfoCursor c = configInfoSelection.query(context);
            if (c.moveToNext())
                configInfoBean =  ConfigInfoBean.newInstance(c.getId(),c.getCid(),c.getType(),c.getTitle(),c.getSummary(),c.getDescription(),c.getVersions(),c.getUpdates(),c.getExpectedVersion(),c.getLatestVersion(),c.getDownloadFrom(),c.getDownloadLink());
            c.close();
        }catch (Exception ignored){
        }
        return configInfoBean;
    }

    private static boolean isEmpty(Context context) {
        try {
            int count = 0;
            ConfigInfoSelection configInfoSelection = new ConfigInfoSelection();
            ConfigInfoCursor c = configInfoSelection.query(context);
            while (c.moveToNext()) {
                count++;
            }
            c.close();
            return count == 0;
        }catch (Exception e){
            return false;
        }
    }

    private static ConfigInfoContentValues prepare(ConfigInfoBean configInfoBean) {
        ConfigInfoContentValues values = new ConfigInfoContentValues();
        values.putCid(configInfoBean.getCid());
        values.putType(configInfoBean.getType());
        values.putTitle(configInfoBean.getTitle());
        values.putSummary(configInfoBean.getSummary());
        values.putDescription(configInfoBean.getDescription());
        values.putVersions(configInfoBean.getVersions());
        values.putUpdates(configInfoBean.getUpdates());
        values.putExpectedVersion(configInfoBean.getExpectedVersion());
        values.putLatestVersion(configInfoBean.getLatestVersion());
        values.putDownloadLink(configInfoBean.getDownloadLink());
        values.putDownloadFrom(configInfoBean.getDownloadFrom());
        return values;
    }


    public void setLatestVersion(Context context, String latestVersion) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return;
        if(configInfoBean.getLatestVersion()!=null && configInfoBean.getLatestVersion().equals(latestVersion)) return ;
        configInfoBean.setLatestVersion(latestVersion);
        insertOrUpdate(context, configInfoBean);
    }
    public static void setDownloadFrom(Context context, String downloadFrom) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return;
        if(configInfoBean.getDownloadFrom()!=null && configInfoBean.getDownloadFrom().equals(downloadFrom)) return ;
        configInfoBean.setDownloadFrom(downloadFrom);
        insertOrUpdate(context, configInfoBean);
    }


    public static String getCid(Context context) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return null;
        return configInfoBean.getCid();
    }
    public static String getType(Context context) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return null;
        return configInfoBean.getType();
    }
    public static String getTitle(Context context) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return null;
        return configInfoBean.getType();
    }
    public static String getSummary(Context context) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return null;
        return configInfoBean.getSummary();
    }
    public static String getDescription(Context context) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return null;
        return configInfoBean.getDescription();
    }
    public static String getVersion(Context context) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return null;
        return configInfoBean.getVersions();
    }
    public static String getUpdate(Context context) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return null;
        return configInfoBean.getUpdates();
    }
    public static String getExpectedVersion(Context context) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return null;
        return configInfoBean.getExpectedVersion();
    }
    public static String getLatestVersion(Context context) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return null;
        return configInfoBean.getLatestVersion();
    }
    public static String getDownloadFrom(Context context) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return null;
        return configInfoBean.getDownloadFrom();
    }
    public static String getDownloadLink(Context context) {
        ConfigInfoBean configInfoBean=read(context);
        if(configInfoBean==null) return null;
        return configInfoBean.getDownloadLink();
    }
}
