package org.md2k.mcerebrum.core.access.studyinfo;

// @formatter:off
import org.md2k.mcerebrum.core.access.base.BaseModel;

import java.util.Date;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/**
 * Study ContentProvider Model class.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
@SuppressWarnings({"WeakerAccess", "unused"})
public interface StudyInfoModel extends BaseModel {

    long getId();

    @Nullable
    String getSid();

    @Nullable
    String getType();

    @Nullable
    String getTitle();

    @Nullable
    String getSummary();

    @Nullable
    String getDescription();

    @Nullable
    String getVersion();

    @Nullable
    String getIcon();

    @Nullable
    String getCoverImage();

    @Nullable
    Boolean getStartAtBoot();

    @Nullable
    Boolean getStarted();
}
