package org.md2k.mcerebrum.core.access.studyinfo;

// @formatter:off
import java.util.Date;

import android.database.Cursor;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import org.md2k.mcerebrum.core.access.base.AbstractCursor;

/**
 * Study ContentProvider Cursor class.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
@SuppressWarnings({"WeakerAccess", "unused", "UnnecessaryLocalVariable"})
public class StudyInfoCursor extends AbstractCursor implements StudyInfoModel {
    public StudyInfoCursor(Cursor cursor) {
        super(cursor);
    }

    @Override
    public long getId() {
        Long res = getLongOrNull(StudyInfoColumns._ID);
        if (res == null)
            throw new NullPointerException("The value of '_id' in the database was null, which is not allowed according to the model definition");
        return res;
    }

    @Nullable
    @Override
    public String getSid() {
        String res = getStringOrNull(StudyInfoColumns.SID);
        return res;
    }

    @Nullable
    @Override
    public String getType() {
        String res = getStringOrNull(StudyInfoColumns.TYPE);
        return res;
    }

    @Nullable
    @Override
    public String getTitle() {
        String res = getStringOrNull(StudyInfoColumns.TITLE);
        return res;
    }

    @Nullable
    @Override
    public String getSummary() {
        String res = getStringOrNull(StudyInfoColumns.SUMMARY);
        return res;
    }

    @Nullable
    @Override
    public String getDescription() {
        String res = getStringOrNull(StudyInfoColumns.DESCRIPTION);
        return res;
    }

    @Nullable
    @Override
    public String getVersion() {
        String res = getStringOrNull(StudyInfoColumns.VERSION);
        return res;
    }

    @Nullable
    @Override
    public String getIcon() {
        String res = getStringOrNull(StudyInfoColumns.ICON);
        return res;
    }

    @Nullable
    @Override
    public String getCoverImage() {
        String res = getStringOrNull(StudyInfoColumns.COVER_IMAGE);
        return res;
    }

    @Nullable
    @Override
    public Boolean getStartAtBoot() {
        Boolean res = getBooleanOrNull(StudyInfoColumns.START_AT_BOOT);
        return res;
    }

    @Nullable
    @Override
    public Boolean getStarted() {
        Boolean res = getBooleanOrNull(StudyInfoColumns.STARTED);
        return res;
    }
}
