package org.md2k.mcerebrum.core.access.base;

// @formatter:off
import android.content.Context;
import android.content.ContentResolver;
import android.content.ContentValues;
import android.net.Uri;

/**
 * Abstract ContentProvider ContentValues class.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
@SuppressWarnings("unused")
public abstract class AbstractContentValues<T extends AbstractContentValues<?>> {
    protected final ContentValues mContentValues = new ContentValues();
    private Boolean mNotify;

    protected abstract Uri baseUri();

    public Uri uri() {
        Uri uri = baseUri();
        if (mNotify != null)
            uri = BaseContentProvider.notify(uri, mNotify);
        return uri;
    }

    @SuppressWarnings("unchecked")
    public T notify(boolean notify) {
        mNotify = notify;
        return (T) this;
    }

    public ContentValues values() {
        return mContentValues;
    }

    public Uri insert(ContentResolver contentResolver) {
        return contentResolver.insert(uri(), values());
    }

    public Uri insert(Context context) {
        return context.getContentResolver().insert(uri(), values());
    }
}
