package org.md2k.mcerebrum.core.access.base;

/**
 * Base ContentProvider Model interface.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
public interface BaseModel {}
