package org.md2k.mcerebrum.core.access.appinfo;

// @formatter:off
import java.util.Date;

import android.database.Cursor;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import org.md2k.mcerebrum.core.access.base.AbstractCursor;

/**
 * App ContentProvider Cursor class.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
@SuppressWarnings({"WeakerAccess", "unused", "UnnecessaryLocalVariable"})
public class AppInfoCursor extends AbstractCursor implements AppInfoModel {
    public AppInfoCursor(Cursor cursor) {
        super(cursor);
    }

    @Override
    public long getId() {
        Long res = getLongOrNull(AppInfoColumns._ID);
        if (res == null)
            throw new NullPointerException("The value of '_id' in the database was null, " +
                    "which is not allowed according to the model definition");
        return res;
    }

    @Nullable
    @Override
    public String getPackageName() {
        String res = getStringOrNull(AppInfoColumns.PACKAGE_NAME);
        return res;
    }

    @Nullable
    @Override
    public String getType() {
        String res = getStringOrNull(AppInfoColumns.TYPE);
        return res;
    }

    @Nullable
    @Override
    public String getTitle() {
        String res = getStringOrNull(AppInfoColumns.TITLE);
        return res;
    }

    @Nullable
    @Override
    public String getSummary() {
        String res = getStringOrNull(AppInfoColumns.SUMMARY);
        return res;
    }

    @Nullable
    @Override
    public String getDescription() {
        String res = getStringOrNull(AppInfoColumns.DESCRIPTION);
        return res;
    }

    @Nullable
    @Override
    public Boolean getUseInStudy() {
        Boolean res = getBooleanOrNull(AppInfoColumns.USE_IN_STUDY);
        return res;
    }

    @Nullable
    @Override
    public String getUseAs() {
        String res = getStringOrNull(AppInfoColumns.USE_AS);
        return res;
    }

    @Nullable
    @Override
    public Boolean getInstalled() {
        Boolean res = getBooleanOrNull(AppInfoColumns.INSTALLED);
        return res;
    }

    @Nullable
    @Override
    public String getDownloadLink() {
        String res = getStringOrNull(AppInfoColumns.DOWNLOAD_LINK);
        return res;
    }

    @Nullable
    @Override
    public String getUpdates() {
        String res = getStringOrNull(AppInfoColumns.UPDATES);
        return res;
    }

    @Nullable
    @Override
    public String getCurrentVersion() {
        String res = getStringOrNull(AppInfoColumns.CURRENT_VERSION);
        return res;
    }

    @Nullable
    @Override
    public String getLatestVersion() {
        String res = getStringOrNull(AppInfoColumns.LATEST_VERSION);
        return res;
    }

    @Nullable
    @Override
    public String getExpectedVersion() {
        String res = getStringOrNull(AppInfoColumns.EXPECTED_VERSION);
        return res;
    }

    @Nullable
    @Override
    public String getIcon() {
        String res = getStringOrNull(AppInfoColumns.ICON);
        return res;
    }

    @Nullable
    @Override
    public Boolean getMcerebrumSupported() {
        Boolean res = getBooleanOrNull(AppInfoColumns.MCEREBRUM_SUPPORTED);
        return res;
    }

    @Nullable
    @Override
    public String getFuncInitialize() {
        String res = getStringOrNull(AppInfoColumns.FUNC_INITIALIZE);
        return res;
    }

    @Nullable
    @Override
    public Boolean getInitialized() {
        Boolean res = getBooleanOrNull(AppInfoColumns.INITIALIZED);
        return res;
    }

    @Nullable
    @Override
    public String getFuncUpdateInfo() {
        String res = getStringOrNull(AppInfoColumns.FUNC_UPDATE_INFO);
        return res;
    }

    @Nullable
    @Override
    public String getFuncConfigure() {
        String res = getStringOrNull(AppInfoColumns.FUNC_CONFIGURE);
        return res;
    }

    @Nullable
    @Override
    public Boolean getConfigured() {
        Boolean res = getBooleanOrNull(AppInfoColumns.CONFIGURED);
        return res;
    }

    @Nullable
    @Override
    public Boolean getConfigureMatch() {
        Boolean res = getBooleanOrNull(AppInfoColumns.CONFIGURE_MATCH);
        return res;
    }

    @Nullable
    @Override
    public String getFuncPermission() {
        String res = getStringOrNull(AppInfoColumns.FUNC_PERMISSION);
        return res;
    }

    @Nullable
    @Override
    public Boolean getPermissionOk() {
        Boolean res = getBooleanOrNull(AppInfoColumns.PERMISSION_OK);
        return res;
    }

    @Nullable
    @Override
    public String getFuncBackground() {
        String res = getStringOrNull(AppInfoColumns.FUNC_BACKGROUND);
        return res;
    }

    @Nullable
    @Override
    public Boolean getBackgroundRunningTime() {
        Boolean res = getBooleanOrNull(AppInfoColumns.BACKGROUND_RUNNING_TIME);
        return res;
    }

    @Nullable
    @Override
    public Boolean getIsBackgroundRunning() {
        Boolean res = getBooleanOrNull(AppInfoColumns.IS_BACKGROUND_RUNNING);
        return res;
    }

    @Nullable
    @Override
    public String getFuncReport() {
        String res = getStringOrNull(AppInfoColumns.FUNC_REPORT);
        return res;
    }

    @Nullable
    @Override
    public String getFuncClear() {
        String res = getStringOrNull(AppInfoColumns.FUNC_CLEAR);
        return res;
    }

    @Nullable
    @Override
    public Boolean getDatakitConnected() {
        Boolean res = getBooleanOrNull(AppInfoColumns.DATAKIT_CONNECTED);
        return res;
    }
}
