package org.md2k.mcerebrum.core.access.serverinfo;

// @formatter:off
import org.md2k.mcerebrum.core.access.base.BaseModel;

import java.util.Date;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/**
 * Server ContentProvider Model class.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
@SuppressWarnings({"WeakerAccess", "unused"})
public interface ServerInfoModel extends BaseModel {

    long getId();

    @Nullable
    String getServerAddress();

    @Nullable
    String getUsername();

    @Nullable
    String getUuid();

    @Nullable
    String getPasswordHash();

    @Nullable
    String getToken();

    @Nullable
    String getFileName();

    @Nullable
    String getCurrentVersion();

    @Nullable
    String getLatestVersion();
}
