package org.md2k.mcerebrum.core.access.userinfo;

import org.md2k.mcerebrum.core.access.base.BaseModel;

import java.util.Date;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

/**
 * User ContentProvider Model class.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
@SuppressWarnings({"WeakerAccess", "unused"})
public interface UserInfoModel extends BaseModel {

    long getId();

    @Nullable
    String getUid();

    @Nullable
    String getType();

    @Nullable
    String getUsername();
}
