package org.md2k.mcerebrum.core.access.userinfo;

import java.util.Date;

import android.database.Cursor;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import org.md2k.mcerebrum.core.access.base.AbstractCursor;

/**
 * User ContentProvider Cursor class.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
@SuppressWarnings({"WeakerAccess", "unused", "UnnecessaryLocalVariable"})
public class UserInfoCursor extends AbstractCursor implements UserInfoModel {
    public UserInfoCursor(Cursor cursor) {
        super(cursor);
    }

    @Override
    public long getId() {
        Long res = getLongOrNull(UserInfoColumns._ID);
        if (res == null)
            throw new NullPointerException("The value of '_id' in the database was null, which is " +
                    "not allowed according to the model definition");
        return res;
    }

    @Nullable
    @Override
    public String getUid() {
        String res = getStringOrNull(UserInfoColumns.UID);
        return res;
    }

    @Nullable
    @Override
    public String getType() {
        String res = getStringOrNull(UserInfoColumns.TYPE);
        return res;
    }

    @Nullable
    @Override
    public String getUsername() {
        String res = getStringOrNull(UserInfoColumns.USERNAME);
        return res;
    }
}
