package org.md2k.mcerebrum.core.access.userinfo;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

import org.md2k.mcerebrum.core.access.SampleProviderSQLiteOpenHelper;
import org.md2k.mcerebrum.core.access.userinfo.UserInfoBean;
import org.md2k.mcerebrum.core.access.userinfo.UserInfoCursor;
import org.md2k.mcerebrum.core.access.userinfo.UserInfoSelection;
import org.md2k.mcerebrum.core.access.userinfo.UserInfoBean;
import org.md2k.mcerebrum.core.access.userinfo.UserInfoColumns;
import org.md2k.mcerebrum.core.access.userinfo.UserInfoContentValues;
import org.md2k.mcerebrum.core.access.userinfo.UserInfoCursor;
import org.md2k.mcerebrum.core.access.userinfo.UserInfoSelection;

/**
 * User ContentProvider ContentProvider class.
 * This class is auto-generated by Android ContentProvider Generator.
 * For more information see <a href="https://github.com/BoD/android-contentprovider-generator">GitHub</a>.
 */
public class UserCP {

    public static void deleteTable(Context context) {
        try {
            SampleProviderSQLiteOpenHelper s = SampleProviderSQLiteOpenHelper.getInstance(context);
            SQLiteDatabase db = s.getWritableDatabase();
            db.execSQL("DROP TABLE IF EXISTS " + UserInfoColumns.TABLE_NAME);
            db.execSQL(SampleProviderSQLiteOpenHelper.SQL_CREATE_TABLE_USER_INFO);
        }catch (Exception e){}
    }

    public static void insertOrUpdate(Context context, UserInfoBean userInfoBean) {
        try {
            UserInfoContentValues values = prepare(userInfoBean);
            if (isEmpty(context))
                values.insert(context);
            else
                values.update(context, new UserInfoSelection().uid(userInfoBean.getUid()));
        }catch (Exception e){
            deleteTable(context);
            UserInfoContentValues values = prepare(userInfoBean);
            values.insert(context);
        }
    }

    private static UserInfoBean read(Context context) {
        UserInfoBean userInfoBean = null;
        try {
            UserInfoSelection userInfoSelection = new UserInfoSelection();
            UserInfoCursor u = userInfoSelection.query(context);
            if (u.moveToNext())
                userInfoBean = UserInfoBean.newInstance(u.getId(), u.getUid(), u.getType(), u.getUsername());
            u.close();
        } catch (Exception ignored) {}
        return userInfoBean;
    }

    public static boolean isEmpty(Context context) {
        int count = 0;
        UserInfoSelection userInfoSelection = new UserInfoSelection();
        UserInfoCursor c = userInfoSelection.query(context);
        while (c.moveToNext()) {
            count++;
        }
        c.close();
        return count == 0;
    }

    private static UserInfoContentValues prepare(UserInfoBean userInfoBean) {
        UserInfoContentValues values = new UserInfoContentValues();
        values.putUsername(userInfoBean.getUsername());
        values.putType(userInfoBean.getType());
        values.putUid(userInfoBean.getUid());
        return values;
    }

    public static void set(Context context, String type, String userName) {
        UserInfoBean userInfoBean = read(context);
        if (userInfoBean == null)
            userInfoBean = new UserInfoBean();
        userInfoBean.setType(type);
        userInfoBean.setUsername(userName);
        insertOrUpdate(context, userInfoBean);
    }

    public static String getUserName(Context context) {
        UserInfoBean userInfoBean = read(context);
        if (userInfoBean == null)
            return null;
        return userInfoBean.getUsername();
    }
}
