language: android
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-support
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_6ed7ad129a42_key -iv $encrypted_6ed7ad129a42_iv -in motionsense/release-key.keystore.enc -out motionsense/release-key.keystore -d
- git clone https://github.com/MD2Korg/mCerebrum-Utilities.git /home/travis/build/MD2Korg/mCerebrum-Utilities
- git clone https://github.com/MD2Korg/mCerebrum-DataKitAPI.git /home/travis/build/MD2Korg/mCerebrum-DataKitAPI
script:
- "./gradlew assembleRelease"
deploy:
  file_glob: true
  provider: releases
  api_key:
    secure: mJ9YgqiGQZXe2FAP08gzjDqkYd6d/8kqkY6dwDPDxNWTmxkWeYJHsXh0nH5m3PaDKAPbu77TYy7P4J4Q6YCGqlI/GhTN9Ej/0pacZth3mdfLnT+KcaTWEXFz6lIp/XkhBAh2SN+m7HCYbLqyaQT6Xz2wuA3mun6cHpGmjA3wRgj9Uyj6psUDaCv8a+mR++R4uvNxoomK3h2YysfUh5xZxgzJSM54awOA5E9BLni7tpy2JravWAI726U2odrqY5sfCxYoWz6aJjREWFdIKHwLaWO/rhi5DscDhSN3z6KUMBCBhySgPL3feU+TRDQchXDRH0Tb2pEsfx6NZI57aERVOsHvFt8Nv91nXX88fP+pdVXd55pCszanSinWNFHCRaXUjNHj7fWD6cqz5pwlB5bVgmEa96QwshOGuOtdRfM+ix+z8lRjs4vFjc7xOz6D9jejfHaYQRtuTL1r0/IrCw3svvJpaFiKhnxbqWsh5xyLrurvrfs8ajgbYmTtcAMWSGGoS4G7MmLpJGy/ATm33/ml6IN4mkTlPBZB6zhNwnr/L54X7kyTB+9uMewF/3f7v3PQHukmAHpQwljRn2Ayvs2y66sM17ITdyjet1P/v4KYBu3kZPkiXvHZef0QLHql8F/wGPcgvUnEJKkQcbrSAw3+kdaxFHhI90lDoaQPL24b7ik=
  file: motionsense/build/outputs/apk/motionsense*.*.*.apk
  on:
    repo: MD2Korg/mCerebrum-MotionSense
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: SeEHFnate38xgC8ZxkeZhd9IZUcp2EAV7uluq6/cTHDuFdHGOrME3EqD68uA2V6dulxEGA3dmiwLB6M6YRyP9xnJ8TgE7eTTj9XGcB7ajhIIZY3LutRIhotomQWh/ekMeF+xS48RyPsK31GxWbpsSdr+Si05hLLnyLBoteHOc+N1bP83YJRi0HqgqT8VawVe2gVpY8DDoI9SbRljU1gh43sg7UwKVPiQN5see9fJ102NN+CdwCjO8Bn9HFc0AFB0oLTuKLsnwCBd/cXL6DD3QUldoei+EIky1NQscSTGPUOYbg4i58xK9vWj+cZ/0IVyBJgGex6rHfb0oQHjgb6SXrfen+//T4NVHrI9G98zOZPfN1sNFzPq1RUEzVAVg4uv/BQg02SbG2zcegl54/BKOPToSIDWfJdeiwLQkMDWV+WvDKQsEp2lR8Cgmk5IQ2IugCbhwJR+mMfy3zay7Sydqxkc5fLF4TqXw8l5JCttcGzk3piBXpzsNMkSAmAFkMtktTNRsazjwEfO98PVWy6v5CytodGJ2FzCYtDprjl0GTMqIxA+1nKhOSxYzYKsse/uJpcGBfXITmnRTxONix3TM9q98H0lBzWWKUfgxwStTTf9vlsolqD43PzAYyGkqkq9rYXX75X1BMikENW7YSpH+djYM79eVXG3wpwoSKvEHwo=
  - secure: NbVpPiR9qgEdC5HO1/Y7f2aAB4jglfU20PRx+p1G0w1TkyxoPb8tbjjsyNlt4E5mz6SyLU7kXT+9mMyCaJQPTdelQOuGfWo4TjrZfBzdJ/TDB75AzdMAej7cWEphrCDpkxabKLiRkFs//vhDwCXa+PLUSpRkJkaEHiblhzS2iebEG0JYz7M7BScppRfq4/EvFaoSlqVLJfEZ3lYX5X8TgeXpS7cPILU7NOgY28jIKEz8BTUAH2dLgjLwXGJUJv4nQPqyJ9/1NSzSi/ST9oL7iJsZx94JsJCAsFPEl5fACmWJQMjcSTXHlTz4Vtoq2DrWTLCN4o+gOPjKX7NYI4hiWLi4am+myRIq7nbnKvnAbk9tKvRlPEMaSRenUz+v5+40zDRWsvK9giXg0jxKPuRfW4D5z/fQor7PsBa5M373vkqRvQDpl62udaPpu77PPU5EPLpfzpv4wVHMIR5f+Yljop3i3xKQhtJiESjspHO+y+Xlyr5lFOdbqIE9TLgEBTpV1rfTjm/ZeLaPAif2kjeYVRV9Nn8mZ4NgJga58jwGiuR024jWcT536YyJmJCt3+wbBpSrSSLzX4woU6e+hfygRjKdoKoPwQ8CGRRGAJ4vMcX6H0ucnokD86JHUVROj6s1zbcVGPBA40ms/tKt4qDgKAtQbkZtt384JwEqCDrGdTk=
  - secure: XTnqHYN4CdR0fiWUeAtY5+qsdCh4UlVfd2H+8s4vEiAlK7vuXSVrbUlbe2fVGrXq7K7ejQaYBe7DyEGmDsgtkIGdpZ0qc7B4hkeAL+qQeilDhcs1nusJhg/I+VTDbcsyV1jCJgbcvENldUcenKCJywqwRezOTYtewyYlXDKgQXnQCV21t2hrpd/XcT8iCfTfNCdLw5eiAEyy1iZJfEO3AzTZFZYiMXCF+62FagdjjDwkhnV0Kg1F3Aq9Yto34RVt/XQjQGZkH1lnLWgkk6/yWdLMrxzN9/5vKtnDKyVaBxDPDtXRLG5HAWUT3fwEsTdbiXpEGHZxCItzQOCKuqA6C/Ioa3n5yP9shnJ42a0oWGeQ0Sekdm02iGDfcWFG6KufF49zIvwv3HoVeXhczlh4IVSw5IGFuJQqoVmBBK+sez5MYqNnlHIkts/ZZCeVmo76+Mku/NjiPoeofcdrys1Xs9EbiKP92lQZUMhtcNqQ5r1wf/r3wlDfIJaYTO6DrR8Qfz4PNSXJiVGz7KHPhKHbqBNKcbwAd4xUAgdpLjlkfpuMblYGcKhcl5INus23tC36qZ5U8PHW4U7UNKxgOYIkGNzS4yj4u/O5lgVMvNpjJpN+4OKv4R3EZAVykaTFqTckPVTPeXrcKqf/FWDH0/Rc3nG+O3Zkn4/ESQgxZTCCaWk=
  - secure: pNmf2MzhJP7jzQ2yafeUqAr6WUdry0DB8oG9FIC3XxS/RFBQ26FYhQsfh5/8B5T2wgf+1v8J6vKf9bDXPCE5dSymXAgIcr8SgpOGTYmGDxb0zmVruq9L2eTRfg+RCZIU0x/0/37m83fyeD89Hi8w4ikjLlGQVB+atGARIzU2esuEKodFQZpalb6uJXcdcx0QLbGC5R6TcChhQ83j2kVvJzzyLz4OO27M6hFqBgodjGyMyxzKHipB13QSVCowXmLp5K7yLsG0sq14T3JUxWgl69XUvSQYjN1pk+i/Z6eV7gKfUgkOD1eoM3MmXG8bPuqx+8XeK5NC9YVkRwoBNXQpwM70vw2UX85grX6D0jCjBkyYHnyisiFtebQrWq0Hh1CndTn/VR00C6R0Jc4749VOrdTWEf/qIV+JiH4tEkcne5w2ApAes1zJpjfY0jEi/EC2lO9yNrC0hz30CTlZky/NfGo26B8hIs0miCBnsJM8OUYXkuFoO3PmZdytwQomPyV1IEb5VDjk6N7Q9fbQmK0tNSuu4dSCyZgyV96tNRS+/SHkjFzqpxTqqfR2++6O0tukGVl5qwMoXwnBIdY+E3TCG0kvGTY3Ig7RmUiKMUdoqlOZvDHgKof9WOk8jzrtksWkAafRFX/F5CTGve4imqq0WNMW/U7/Os5CKN/HG73aWTY=
